/**
 * This file is autogenerated by helper.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/helper/contract";

const deployedContracts = {
  11155111: {
    FHETetris: {
      address: "0xb1830b6dFC72B20A60572319ab876341FC69Ff11",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "player",
              type: "address",
            },
          ],
          name: "fetchScores",
          outputs: [
            {
              internalType: "euint32[]",
              name: "scores",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "externalEuint32",
              name: "encryptedScore",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proof",
              type: "bytes",
            },
          ],
          name: "uploadScore",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9368216,
    },
  },
  31337: {
    FHETetris: {
      address: "0x73511669fd4dE447feD18BB79bAFeAC93aB7F31f",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "player",
              type: "address",
            },
          ],
          name: "fetchScores",
          outputs: [
            {
              internalType: "euint32[]",
              name: "scores",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolId",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "externalEuint32",
              name: "encryptedScore",
              type: "bytes32",
            },
            {
              internalType: "bytes",
              name: "proof",
              type: "bytes",
            },
          ],
          name: "uploadScore",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 9368216,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
